jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
        STACK_YAML: stack.yaml
      stack-lts-12:
        BUILD: stack
        ARGS: "--resolver lts-12.26"
      stack-lts-11:
        BUILD: stack
        ARGS: "--resolver lts-11"
    maxParallel: 6
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack --install-ghc $ARGS test --only-dependencies
      stack $ARGS test
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
