name: Stackage nightly

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: |
          ~/.stack
          ~/.stack-work
          ~/.ghc
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build nightly
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        rm -fr discord-bot playground dist-newstyle
        rm -f stack.yaml
        stack init --resolver nightly \
          && echo "::set-env name=passed::true" \
          || echo "::set-env name=passed::false"
        stack build --resolver nightly --haddock --test --only-dependencies --bench --no-run-benchmarks \
          && echo "::set-env name=passed::true" \
          || echo "::set-env name=passed::false"
    - name: Test nightly
      if: env.passed == 'true'
      run: |
        stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
    - name: Report status
      if: env.passed == 'false'
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          Warning: Failed to build against stack nightly.
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default
